version: "3.8"

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: observers
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    restart: always
    build: ./observers/backend
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    stdin_open: true
    volumes:
      - ./:/observers/backend
    environment:
      SECRET_KEY: YOUR_SECRET_KEY
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: observers

  frontend:
    restart: always
    build: ./observers/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./:/observers/frontend
    environment:
      REACT_APP_CLIENT_ID: YOUR_IMGUR_API_KEY
      REACT_APP_LOCAL_NETWORK_IP: YOUR_LOCAL_NETWORK_IP

volumes:
  db-data: